name: json_storage
description: A simple json storage for Dart.
version: 1.0.0
repository: https://github.com/matheusoreis/DartJsonStorage

environment:
  sdk: ^3.4.3

dependencies:
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.7
