name: json_storage
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  path: ^1.9.0

dev_dependencies:
  test: ^1.24.0
